on:
  push:
    paths:
      - 'DESCRIPTION'

name: Commands
jobs:
  document-and-dispatch:
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: system dependencies
        run: sudo apt-get install libcurl4-openssl-dev libnode-dev
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("remotes", "roxygen2"))' -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'
      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Documentation' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: lukaswallrich/timesaveR
          event-type: ready
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
