on:
  push:
    paths:
      - 'DESCRIPTION'

name: Document-and-check

jobs:
  document-and-dispatch:
    name: document
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: system dependencies
        run: sudo apt-get install libcurl4-openssl-dev libnode-dev
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("remotes", "roxygen2", "rcmdcheck"))' -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Document
        run: Rscript -e 'roxygen2::roxygenise()'
      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Documentation' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      - name: test
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")'
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: rcmdcheck-results
          path: check
